/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as UiRouteImport } from './routes/ui'
import { Route as ContaServicosRouteImport } from './routes/conta_.servicos'
import { Route as EntrarVerificarRouteImport } from './routes/entrar_.verificar'
import { Route as PerfilUserIdRouteImport } from './routes/perfil.$userId'
import { Route as ServicosServiceIdRouteImport } from './routes/servicos_.$serviceId'
import { Route as ContaServicosServiceIdRouteImport } from './routes/conta_.servicos_.$serviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaServicosRoute = ContaServicosRouteImport.update({
  id: '/conta_/servicos',
  path: '/conta/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarVerificarRoute = EntrarVerificarRouteImport.update({
  id: '/entrar_/verificar',
  path: '/entrar/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilUserIdRoute = PerfilUserIdRouteImport.update({
  id: '/perfil/$userId',
  path: '/perfil/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosServiceIdRoute = ServicosServiceIdRouteImport.update({
  id: '/servicos_/$serviceId',
  path: '/servicos/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaServicosServiceIdRoute = ContaServicosServiceIdRouteImport.update({
  id: '/conta_/servicos_/$serviceId',
  path: '/conta/servicos/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/publicar': typeof PublicarRoute
  '/servicos': typeof ServicosRoute
  '/ui': typeof UiRoute
  '/conta/servicos': typeof ContaServicosRoute
  '/entrar/verificar': typeof EntrarVerificarRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/servicos/$serviceId': typeof ServicosServiceIdRoute
  '/conta/servicos/$serviceId': typeof ContaServicosServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/publicar': typeof PublicarRoute
  '/servicos': typeof ServicosRoute
  '/ui': typeof UiRoute
  '/conta/servicos': typeof ContaServicosRoute
  '/entrar/verificar': typeof EntrarVerificarRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/servicos/$serviceId': typeof ServicosServiceIdRoute
  '/conta/servicos/$serviceId': typeof ContaServicosServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/publicar': typeof PublicarRoute
  '/servicos': typeof ServicosRoute
  '/ui': typeof UiRoute
  '/conta_/servicos': typeof ContaServicosRoute
  '/entrar_/verificar': typeof EntrarVerificarRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/servicos_/$serviceId': typeof ServicosServiceIdRoute
  '/conta_/servicos_/$serviceId': typeof ContaServicosServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/buscar'
    | '/cadastro'
    | '/conta'
    | '/entrar'
    | '/favoritos'
    | '/publicar'
    | '/servicos'
    | '/ui'
    | '/conta/servicos'
    | '/entrar/verificar'
    | '/perfil/$userId'
    | '/servicos/$serviceId'
    | '/conta/servicos/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/buscar'
    | '/cadastro'
    | '/conta'
    | '/entrar'
    | '/favoritos'
    | '/publicar'
    | '/servicos'
    | '/ui'
    | '/conta/servicos'
    | '/entrar/verificar'
    | '/perfil/$userId'
    | '/servicos/$serviceId'
    | '/conta/servicos/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/buscar'
    | '/cadastro'
    | '/conta'
    | '/entrar'
    | '/favoritos'
    | '/publicar'
    | '/servicos'
    | '/ui'
    | '/conta_/servicos'
    | '/entrar_/verificar'
    | '/perfil/$userId'
    | '/servicos_/$serviceId'
    | '/conta_/servicos_/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuscarRoute: typeof BuscarRoute
  CadastroRoute: typeof CadastroRoute
  ContaRoute: typeof ContaRoute
  EntrarRoute: typeof EntrarRoute
  FavoritosRoute: typeof FavoritosRoute
  PublicarRoute: typeof PublicarRoute
  ServicosRoute: typeof ServicosRoute
  UiRoute: typeof UiRoute
  ContaServicosRoute: typeof ContaServicosRoute
  EntrarVerificarRoute: typeof EntrarVerificarRoute
  PerfilUserIdRoute: typeof PerfilUserIdRoute
  ServicosServiceIdRoute: typeof ServicosServiceIdRoute
  ContaServicosServiceIdRoute: typeof ContaServicosServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta_/servicos': {
      id: '/conta_/servicos'
      path: '/conta/servicos'
      fullPath: '/conta/servicos'
      preLoaderRoute: typeof ContaServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar_/verificar': {
      id: '/entrar_/verificar'
      path: '/entrar/verificar'
      fullPath: '/entrar/verificar'
      preLoaderRoute: typeof EntrarVerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$userId': {
      id: '/perfil/$userId'
      path: '/perfil/$userId'
      fullPath: '/perfil/$userId'
      preLoaderRoute: typeof PerfilUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos_/$serviceId': {
      id: '/servicos_/$serviceId'
      path: '/servicos/$serviceId'
      fullPath: '/servicos/$serviceId'
      preLoaderRoute: typeof ServicosServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta_/servicos_/$serviceId': {
      id: '/conta_/servicos_/$serviceId'
      path: '/conta/servicos/$serviceId'
      fullPath: '/conta/servicos/$serviceId'
      preLoaderRoute: typeof ContaServicosServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuscarRoute: BuscarRoute,
  CadastroRoute: CadastroRoute,
  ContaRoute: ContaRoute,
  EntrarRoute: EntrarRoute,
  FavoritosRoute: FavoritosRoute,
  PublicarRoute: PublicarRoute,
  ServicosRoute: ServicosRoute,
  UiRoute: UiRoute,
  ContaServicosRoute: ContaServicosRoute,
  EntrarVerificarRoute: EntrarVerificarRoute,
  PerfilUserIdRoute: PerfilUserIdRoute,
  ServicosServiceIdRoute: ServicosServiceIdRoute,
  ContaServicosServiceIdRoute: ContaServicosServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
