import {
	type LucideIcon,
	ShieldQuestion,
	AlertTriangle,
	ArrowLeft,
	BrushCleaning,
	Building,
	Calendar,
	CalendarIcon,
	CalendarX,
	Camera,
	Check,
	CheckIcon,
	ChevronDown,
	ChevronDownIcon,
	ChevronLeftIcon,
	ChevronRight,
	ChevronRightIcon,
	ChevronsUpDown,
	ChevronUp,
	ChevronUpIcon,
	Circle,
	CircleAlert,
	CircleCheck,
	CircleIcon,
	Clock,
	Contact,
	Copy,
	Download,
	Edit,
	ExternalLink,
	Eye,
	EyeOff,
	File,
	FileDown,
	FileQuestion,
	FileText,
	Funnel,
	Globe,
	GlobeLock,
	History,
	Home,
	Hourglass,
	Info,
	Key,
	Loader2,
	Lock,
	LogOut,
	Mail,
	MapPin,
	Menu,
	Minus,
	Monitor,
	Moon,
	Plus,
	QrCode,
	RefreshCw,
	RotateCcw,
	Save,
	ScrollText,
	Search,
	Server,
	Settings,
	Shield,
	ShieldCheck,
	ShieldX,
	Sun,
	Trash2,
	Upload,
	User,
	Users,
	UsersRound,
	X,
	LayoutGrid,
	ScanFace,
	ArrowRight,
	GitCompare,
	Bell,
	UserCheck,
	MoreVertical,
} from 'lucide-react'

const icons = {
	eye: Eye,
	eyeOff: EyeOff,
	loader2: Loader2,
	x: X,
	menu: Menu,
	home: Home,
	users: Users,
	'shield-check': ShieldCheck,
	'shield-x': ShieldX,
	lock: Lock,
	'scroll-text': ScrollText,
	history: History,
	settings: Settings,
	search: Search,
	'arrow-left': ArrowLeft,
	'arrow-right': ArrowRight,
	'git-compare': GitCompare,
	'file-question': FileQuestion,
	moon: Moon,
	sun: Sun,
	check: Check,
	circle: Circle,
	'chevron-right': ChevronRight,
	funnel: Funnel,
	'brush-cleaning': BrushCleaning,
	'file-down': FileDown,
	'log-out': LogOut,
	'chevrons-up-down': ChevronsUpDown,
	user: User,
	'calendar-icon': CalendarIcon,
	server: Server,
	info: Info,
	'map-pin': MapPin,
	clock: Clock,
	shield: Shield,
	edit: Edit,
	trash2: Trash2,
	calendar: Calendar,
	plus: Plus,
	building: Building,
	globe: Globe,
	minus: Minus,
	monitor: Monitor,
	save: Save,
	'rotate-ccw': RotateCcw,
	'circle-alert': CircleAlert,
	'qr-code': QrCode,
	camera: Camera,
	upload: Upload,
	'chevron-down': ChevronDown,
	'chevron-up': ChevronUp,
	'circle-icon': CircleIcon,
	'check-icon': CheckIcon,
	'alert-triangle': AlertTriangle,
	'refresh-cw': RefreshCw,
	'chevron-up-icon': ChevronUpIcon,
	'chevron-down-icon': ChevronDownIcon,
	'chevron-left-icon': ChevronLeftIcon,
	'chevron-right-icon': ChevronRightIcon,
	'circle-check': CircleCheck,
	file: File,
	'globe-lock': GlobeLock,
	'calendar-x': CalendarX,
	mail: Mail,
	contact: Contact,
	'external-link': ExternalLink,
	copy: Copy,
	key: Key,
	'file-text': FileText,
	hourglass: Hourglass,
	'users-round': UsersRound,
	download: Download,
	'shield-question': ShieldQuestion,
	'layout-grid': LayoutGrid,
	'scan-face': ScanFace,
	'bell': Bell,
	'user-check': UserCheck,
	'more-vertical': MoreVertical,
}

export type IconName = keyof typeof icons

export type IconProps = React.ComponentProps<LucideIcon> & {
	name: IconName
}

export const Icon: React.FC<IconProps> = ({
	name,
	className,
	size = 20,
	strokeWidth = 2,
	...props
}) => {
	const LucideIcon = icons[name]
	return (
		<LucideIcon
			className={className}
			size={size}
			strokeWidth={strokeWidth}
			{...props}
		/>
	)
}
